### ISSUE TITLE
Access denied when importing TextToSpeech

### ISSUE THREAD

**Issue by upq** [ARBML/klaam#17]
![Untitled](https://user-images.githubusercontent.com/5780280/158056184-91ef287c-0dab-46f1-86d0-27efa5783776.png)

**Comment by zaidalyafeai** [comment]
Can't regenerate that on colab, it seems to work fine 
![image](https://user-images.githubusercontent.com/15667714/165003238-18fd838c-ab91-464b-84f0-f697b9fb0f81.png)

**Comment by upq** [comment]
Of course it wont because you are the owner of the file :).
Try different new accounts to regenerate the error, if it persists a simple change in the permissions of the file on drive to ```anyone with link``` will fix the issue.
Thanks.

**Comment by zaidalyafeai** [comment]
Already have that set to anyone with link. Also tried on another account, it works fine. Can you try again? Or try accessing the link?

**Comment by upq** [comment]
Everything works thanks

**Comment by MagedSaeed** [comment]
If I try to open this link [ https://drive.google.com/uc?id=1J7ZP_q-6mryXUhZ-8j9-RIItz2nJGOIX ] in the browser, it will give me, for the first time, a page saying that this file is large, do you want to download anyways? I think this is the root cause of this issue. After inspecting the download page, I think we should add confirm=t as in the form submitted by the `download anyway` button. Inspiration [ https://stackoverflow.com/a/71176719/4412324 ]

The resulting url  should be https://drive.google.com/uc?id=1J7ZP_q-6mryXUhZ-8j9-RIItz2nJGOIX&confirm=t

I tried on my machine without `confirm=t` and it gives me the access denied message. But works fine when with url: https://drive.google.com/uc?id=1J7ZP_q-6mryXUhZ-8j9-RIItz2nJGOIX&confirm=t

I think we should update the url @zaidalyafeai
